export const projectsData = [
  {
    id: 1,
    name: "SetraStore",
    description: "E-commerce storefront web app.",
    date: "2026-04-17",
    link: "https://setrastore.vercel.app/",
  },
  {
    id: 2,
    name: "Rayaa360",
    description: "Cloud platform website (Rayaa360).",
    date: "2026-04-17",
    link: "https://rayaa360.cloud/",
  },
  {
    id: 3,
    name: "Jumia Clone",
    description: "E-commerce marketplace UI clone.",
    date: "2024-04-23",
    link: "https://jumia-clone-project.vercel.app",
  },
  {
    id: 4,
    name: "GeoForm App",
    description: "Map + form + saved locations list.",
    date: "2024-7-21",
    link: "https://geo-form.vercel.app/",
  },
  {
    id: 5,
    name: "Far-Away-App",
    description: "Travel packing list app.",
    date: "2024-6-28",
    link: "https://far-away-travel-list-react-app.vercel.app/",
  },
  {
    id: 6,
    name: "Disney+ Clone",
    description: "Disney+ streaming UI clone.",
    date: "2023-10-15",
    link: "https://disneyplus-ntabucejo.vercel.app/",
  },
  {
    id: 7,
    name: "Quiz App",
    description: "Quiz app with score tracking.",
    date: "2023-10-15",
    link: "https://quiz-app-ebon-alpha.vercel.app/",
  },
  {
    id: 8,
    name: "ToDo list",
    description: "Simple to-do list app.",
    date: "2022-09-10",
    link: "https://scintillating-lolly-5ae4e4.netlify.app/",
  },
  {
    id: 9,
    name: "Memory Game",
    description: "Card matching memory game.",
    date: "2022-05-30",
    link: "https://memory-game-drab-six.vercel.app/",
  },
  {
    id: 10,
    name: "Hangman Game",
    description: "Hangman word guessing game.",
    date: "2023-07-15",
    link: "https://hangman-game-p4gg.vercel.app/",
  },
  {
    id: 11,
    name: "ChatGpt Clone",
    description: "ChatGPT-style chat UI clone.",
    date: "2023-05-01",
    link: "https://github.com/MahmoudHosni2000/-AIChatter",
  },
  {
    id: 12,
    name: "SpaceX LandingPage",
    description: "Responsive SpaceX-style landing page.",
    date: "2022-10-18",
    link: "https://mellifluous-longma-04a2c8.netlify.app/",
  },
  {
    id: 13,
    name: "Tourism LandingPage",
    description: "Tourism landing page design.",
    date: "2022-09-20",
    link: "https://friendly-crumble-283808.netlify.app/",
  },
];

export const BtnList = [
  { label: "Home", link: "/", icon: "home", newTab: false },
  { label: "About", link: "/about", icon: "about", newTab: false },
  { label: "Projects", link: "/projects", icon: "projects", newTab: false },
  { label: "Contact", link: "/contact", icon: "contact", newTab: false },
  {
    label: "Github",
    link: "https://github.com/MahmoudHosni2000",
    icon: "github",
    newTab: true,
  },
  {
    label: "LinkedIn",
    link: "https://www.linkedin.com/in/mahmoudhosni2000/",
    icon: "linkedin",
    newTab: true,
  },
  {
    label: "Telegram",
    link: "https://t.me/MahmoudHosni0007",
    icon: "Telegram",
    newTab: true,
  },
  {
    label: "Resume",
    link: "/resume.pdf",
    icon: "resume",
    newTab: true,
  },
];


